# Generated by Django 4.2.4 on 2023-12-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminarioapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO ASISTEN', 'No Asisten')], default='RESERVADO', max_length=50),
        ),
    ]
