# Generated by Django 4.2.4 on 2023-12-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminarioapi', '0002_alter_inscrito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='direccion',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='institucion',
            name='telefono',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
