# Generated by Django 4.2.4 on 2023-12-20 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminarioapi', '0003_institucion_direccion_institucion_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminarioapi.institucion'),
        ),
    ]
