# Generated by Django 4.2.4 on 2023-12-20 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seminarioapi', '0004_alter_inscrito_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='fechaInscripcion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='horaInscripcion',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
